namespace PhotoAI.Core.Models;

public class MediaTag
{
    public long Id { get; set; }
    public long MediaItemId { get; set; }
    public MediaItem MediaItem { get; set; } = null!;
    public string Tag { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }
    public DateTime DateCreated { get; set; }
}
