<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PhotoAI.Vector</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoAI.Core\PhotoAI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <!-- <PackageReference Include="Qdrant.Client" Version="1.19.0" /> -->
  </ItemGroup>

</Project>
